services:
  network-config:
    networks:
      - easybank

  microservice-base-config:
    extends:
      service: network-config
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      SPRING_RABBITMQ_HOST: "rabbit"

  microservice-config:
    extends:
      service: microservice-base-config
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_PROFILES_ACTIVE: "prod"
    depends_on:
      configserver:
        condition: service_healthy
