server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/loansdb
    username: root
    password: root
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import:
      - "optional:configserver:http://localhost:8071/"
  profiles:
    active:
      - "prod"
  application:
    name: "loans"

management:
  endpoints:
    web:
      exposure:
        include: "*"