services:
  configserver:
    image: "ahilachokkalingam/configserver:v2"
    container_name: "configserver-ms"
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-fields.yml
      service: microservice-base-config
  eurekaserver:
    image: "ahilachokkalingam/eurekaserver:v2"
    container_name: "eurekaserver-ms"
    ports:
      - "8070:8070"
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-fields.yml
      service: microservice-config-server
    depends_on:
      configserver:
        condition: service_healthy
  accounts:
    image: "ahilachokkalingam/accounts:v2"
    container_name: "accounts-ms"
    ports:
      - "8080:8080"
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-fields.yml
      service: microservice-complete-config
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "accounts"
  card:
    image: "ahilachokkalingam/card:v2"
    container_name: "card-ms"
    ports:
      - "9000:9000"
    healthcheck:
      test: "curl --fail --silent localhost:9000/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-fields.yml
      service: microservice-complete-config
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "cards"
  loan:
    image: "ahilachokkalingam/loan:v2"
    container_name: "loan-ms"
    ports:
      - "8090:8090"
    healthcheck:
      test: "curl --fail --silent localhost:8090/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-fields.yml
      service: microservice-complete-config
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "loans"
  gatewayserver:
    image: "ahilachokkalingam/gatewayserver:v2"
    container_name: "gateway-ms"
    ports:
      - "8072:8072"
    extends:
      file: common-fields.yml
      service: microservice-complete-config
    depends_on:
      accounts:
        condition: service_healthy
      card:
        condition: service_healthy
      loan:
        condition: service_healthy
networks:
  easybank:
    driver: "bridge"